<?php
	
	/**
	 * Gluu-oxd-library
	 *
	 * An open source application library for PHP
	 *
	 *
	 * @copyright Copyright (c) 2017, Gluu Inc. (https://gluu.org/)
	 * @license	  MIT   License            : <http://opensource.org/licenses/MIT>
	 *
	 * @package	  Oxd Library by Gluu
	 * @category  Library, Api
	 * @version   3.1.2
	 *
	 * @author    Gluu Inc.          : <https://gluu.org>
	 * @link      Oxd site           : <https://oxd.gluu.org>
	 * @link      Documentation      : <https://gluu.org/docs/oxd/3.0.1/libraries/php/>
	 * @director  Mike Schwartz      : <mike@gluu.org>
	 * @support   Support email      : <support@gluu.org>
	 * @developer Volodya Karapetyan : <https://github.com/karapetyan88> <mr.karapetyan88@gmail.com>
	 *
	 
	 *
	 * This content is released under the MIT License (MIT)
	 *
	 * Copyright (c) 2017, Gluu inc, USA, Austin
	 *
	 * Permission is hereby granted, free of charge, to any person obtaining a copy
	 * of this software and associated documentation files (the "Software"), to deal
	 * in the Software without restriction, including without limitation the rights
	 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	 * copies of the Software, and to permit persons to whom the Software is
	 * furnished to do so, subject to the following conditions:
	 *
	 * The above copyright notice and this permission notice shall be included in
	 * all copies or substantial portions of the Software.
	 *
	 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
	 * THE SOFTWARE.
	 *
	 */
	
	/**
	 * Client authorization class
	 *
	 * Class is connecting to oxd-server via socket, and getting authorization url from gluu-server.
	 *
	 * @package		  Gluu-oxd-library
	 * @subpackage	Libraries
	 * @category	  Relying Party (RP)
	 * @see	        Client_OXD_RP
	 */

require_once 'ClientOXDRP.php';

class GetAuthorizationUrl extends ClientOXDRP
{
    /**start parameter for request!**/
    private $request_oxd_id = null;
    private $request_acr_values = null;
    private $request_prompt = null;
    private $request_scope = null;
    private $request_HD = null;
    /**end request parameter**/

    /**start parameter for response!**/
    private $response_authorization_url;
    /**end response parameter**/
    
    /**
    * @var string $request_access_token     access token for each request
    */
    private $request_access_token;

    function getRequest_access_token() {
        return $this->request_access_token;
    }

    function setRequest_access_token($request_access_token) {
        $this->request_access_token = $request_access_token;
    }

    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getRequestHD()
    {
        return $this->request_HD;
    }

    /**
     * @param null $request_HD
     */
    public function setRequestHD($request_HD)
    {
        $this->request_HD = $request_HD;
    }

    /**
     * @return null
     */
    public function getRequestPrompt()
    {
        return $this->request_prompt;
    }

    /**
     * @return null
     */
    public function getRequestScope()
    {
        return $this->request_scope;
    }

    /**
     * @param null $request_scope
     */
    public function setRequestScope($request_scope)
    {
        $this->request_scope = $request_scope;
    }

    /**
     * @param null $request_prompt
     */
    public function setRequestPrompt($request_prompt)
    {
        $this->request_prompt = $request_prompt;
    }

    /**
     * @return mixed
     */
    public function getResponseOxdNonce()
    {
        if($parts = parse_url($this->getResponseAuthorizationUrl())){
            parse_str($parts['query'], $query);
            return $query['nonce'];
        }else{
            return null;
        }

    }

    /**
     * @return mixed
     */
    public function getResponseOxdClientId()
    {
        if($parts = parse_url($this->getResponseAuthorizationUrl())){
            parse_str($parts['query'], $query);
            return $query['client_id'];
        }else{
            return null;
        }
    }

    /**
     * @return mixed
     */
    public function getResponseOxdClientSecret()
    {
        if($parts = parse_url($this->getResponseAuthorizationUrl())){
            parse_str($parts['query'], $query);
            return $query['client_secret'];
        }else{
            return null;
        }
    }

    /**
     * @return mixed
     */
    public function getResponseOxdRedirectUri()
    {
        if($parts = parse_url($this->getResponseAuthorizationUrl())){
            parse_str($parts['query'], $query);
            return $query['redirect_uri'];
        }else{
            return null;
        }
    }

    /**
     * @return mixed
     */
    public function getResponseOxdScope()
    {
        if($parts = parse_url($this->getResponseAuthorizationUrl())){
            parse_str($parts['query'], $query);
            return $query['scope'];
        }else{
            return null;
        }
    }

    /**
     * @return mixed
     */
    public function getResponseOxdState()
    {
        if($parts = parse_url($this->getResponseAuthorizationUrl())){
            parse_str($parts['query'], $query);
            return $query['state'];
        }else{
            return null;
        }
    }

    /**
     * @return mixed
     */
    public function getResponseResponseType()
    {
        if($parts = parse_url($this->getResponseAuthorizationUrl())){
            parse_str($parts['query'], $query);
            return $query['response_type'];
        }else{
            return null;
        }
    }

    /**
     * @return mixed
     */
    public function getRequestOxdId()
    {
        return $this->request_oxd_id;
    }

    /**
     * @param mixed $request_oxd_id
     */
    public function setRequestOxdId($request_oxd_id)
    {
        $this->request_oxd_id = $request_oxd_id;
    }

    /**
     * @return null
     */
    public function getRequestAcrValues()
    {
        return $this->request_acr_values;
    }

    /**
     * @param null $request_acr_values
     */
    public function setRequestAcrValues($request_acr_values)
    {
        $this->request_acr_values = $request_acr_values;
    }

    /**
     * @return mixed
     */
    public function getResponseAuthorizationUrl()
    {
        $this->response_authorization_url = $this->getResponseData()->authorization_url;
        return $this->response_authorization_url;
    }

    public function setCommand()
    {
        $this->command = 'get_authorization_url';
    }

    public function setParams()
    {
        $this->params = array(
            "oxd_id" => $this->getRequestOxdId(),
            "acr_values" => $this->getRequestAcrValues(),
            "prompt" => $this->getRequestPrompt(),
            "scope" => $this->getRequestScope(),
            "hd" => $this->getRequestHD(),
            "protection_access_token" => $this->getRequest_access_token()
        );
    }

}
