<?php
	
	/**
	 * Gluu-oxd-library
	 *
	 * An open source application library for PHP
	 *
	 *
	 * @copyright Copyright (c) 2017, Gluu Inc. (https://gluu.org/)
	 * @license	  MIT   License            : <http://opensource.org/licenses/MIT>
	 *
	 * @package	  Oxd Library by Gluu
	 * @category  Library, Api
	 * @version   3.1.2
	 *
	 * @author    Gluu Inc.          : <https://gluu.org>
	 * @link      Oxd site           : <https://oxd.gluu.org>
	 * @link      Documentation      : <https://gluu.org/docs/oxd/3.0.1/libraries/php/>
	 * @director  Mike Schwartz      : <mike@gluu.org>
	 * @support   Support email      : <support@gluu.org>
	 * @developer Volodya Karapetyan : <https://github.com/karapetyan88> <mr.karapetyan88@gmail.com>
	 *
	 
	 *
	 * This content is released under the MIT License (MIT)
	 *
	 * Copyright (c) 2017, Gluu inc, USA, Austin
	 *
	 * Permission is hereby granted, free of charge, to any person obtaining a copy
	 * of this software and associated documentation files (the "Software"), to deal
	 * in the Software without restriction, including without limitation the rights
	 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	 * copies of the Software, and to permit persons to whom the Software is
	 * furnished to do so, subject to the following conditions:
	 *
	 * The above copyright notice and this permission notice shall be included in
	 * all copies or substantial portions of the Software.
	 *
	 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
	 * THE SOFTWARE.
	 *
	 */
	
	/**
	 * User information class
	 *
	 * Class is connecting to oxd-server via socket, and getting logedin user information url from gluu-server.
	 *
	 * @package		  Gluu-oxd-library
	 * @subpackage	Libraries
	 * @category	  Relying Party (RP)
	 * @see	        Client_OXD_RP
	 */

	require_once 'ClientOXDRP.php';
	
	class GetUserInfo extends ClientOXDRP
{
    /**start parameter for request!**/
    private $request_oxd_id = null;
    private $request_access_token = null;
    private $request_protection_access_token = null;
    /**end request parameter**/

    /**start parameter for response!**/
    private $response_claims;
    private $response_sub;
    private $response_name;
    private $response_user_name;
    private $response_given_name;
    private $response_family_name;
    private $response_middle_name;
    private $response_nickname;
    private $response_preferred_username;
    private $response_profile;
    private $response_picture;
    private $response_website;
    private $response_email;
    private $response_gender;
    private $response_birthdate;
    private $response_zoneinfo;
    private $response_phone_number;
    private $response_address;
    private $response_updated_at;

    /**end response parameter**/

    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getResponseClaims()
    {
        $this->response_claims = $this->getResponseData()->claims;
        return $this->response_claims;
    }

    /**
     * @return mixed
     */
    public function getResponseUserName()
    {
        $this->response_user_name = $this->getResponseClaims()->user_name[0];
        return $this->response_user_name;
    }

    /**
     * @return mixed
     */
    public function getResponseProfile()
    {
        $this->response_profile = $this->getResponseClaims()->profile[0];
        return $this->response_profile;
    }

    /**
     * @return mixed
     */
    public function getResponsePhoneNumber()
    {
        $this->response_phone_number = $this->getResponseClaims()->phone_number[0];
        return $this->response_phone_number;
    }

    /**
     * @return mixed
     */
    public function getResponseAddress()
    {
        $this->response_address = $this->getResponseClaims()->address[0];
        return $this->response_address;
    }

    /**
     * @return mixed
     */
    public function getResponseUpdatedAt()
    {
        $this->response_updated_at = $this->getResponseClaims()->updated_at[0];
        return $this->response_updated_at;
    }

    /**
     * @return mixed
     */
    public function getResponseZoneinfo()
    {
        $this->response_zoneinfo = $this->getResponseClaims()->zoneinfo[0];
        return $this->response_zoneinfo;
    }

    /**
     * @return mixed
     */
    public function getResponseNickname()
    {
        $this->response_nickname = $this->getResponseClaims()->nickname[0];
        return $this->response_nickname;
    }

    /**
     * @return mixed
     */
    public function getResponseWebsite()
    {
        $this->response_website = $this->getResponseClaims()->website[0];
        return $this->response_website;
    }

    /**
     * @return mixed
     */
    public function getResponseMiddleName()
    {
        $this->response_middle_name = $this->getResponseClaims()->middle_name[0];
        return $this->response_middle_name;
    }
    /**
     * @return mixed
     */
    public function getResponseBirthdate()
    {
        $this->response_birthdate = $this->getResponseClaims()->birthdate[0];
        return $this->response_birthdate;
    }

    /**
     * @return mixed
     */
    public function getResponseGender()
    {
        $this->response_gender = $this->getResponseClaims()->gender[0];
        return $this->response_gender;
    }

    /**
     * @return null
     */
    public function getRequestAccessToken()
    {
        return $this->request_access_token;
    }

    /**
     * @param null $request_access_token
     */
    public function setRequestAccessToken($request_access_token)
    {
        $this->request_access_token = $request_access_token;
    }
    
    /**
     * @return null
     */
    public function getRequestProtectionAccessToken()
    {
        return $this->request_protection_access_token;
    }

    /**
     * @param null $request_access_token
     */
    public function setRequestProtectionAccessToken($request_access_token)
    {
        $this->request_protection_access_token = $request_access_token;
    }

    /**
     * @return mixed
     */
    public function getRequestOxdId()
    {
        return $this->request_oxd_id;
    }

    /**
     * @param mixed $request_oxd_id
     */
    public function setRequestOxdId($request_oxd_id)
    {
        $this->request_oxd_id = $request_oxd_id;
    }

    /**
     * @return mixed
     */
    public function getResponseSub()
    {
        $this->response_sub = $this->getResponseClaims()->sub[0];
        return $this->response_sub;
    }

    /**
     * @return mixed
     */
    public function getResponseName()
    {
        $this->response_name = $this->getResponseClaims()->name[0];
        return $this->response_name;
    }

    /**
     * @return mixed
     */
    public function getResponseGivenName()
    {
        $this->response_given_name = $this->getResponseClaims()->given_name[0];
        return $this->response_given_name;
    }

    /**
     * @return mixed
     */
    public function getResponseFamilyName()
    {
        $this->response_family_name = $this->getResponseClaims()->family_name[0];
        return $this->response_family_name;
    }

    /**
     * @return mixed
     */
    public function getResponsePreferredUsername()
    {
        $this->response_preferred_username = $this->getResponseClaims()->preferred_username[0];
        return $this->response_preferred_username;
    }

    /**
     * @return mixed
     */
    public function getResponseEmail()
    {
        $this->response_email = $this->getResponseClaims()->email[0];
        return $this->response_email;
    }

    /**
     * @return mixed
     */
    public function getResponsePicture()
    {
        $this->response_picture = $this->getResponseClaims()->picture[0];
        return $this->response_picture;
    }

    public function setCommand()
    {
        $this->command = 'get_user_info';
    }

    public function setParams()
    {
        $this->params = array(
            "oxd_id" => $this->getRequestOxdId(),
            "access_token" => $this->getRequestAccessToken(),
            "protection_access_token" => $this->getRequestProtectionAccessToken()
        );
    }

}
